"""Initial migration

Revision ID: 0a9d4dd555ac
Revises: 
Create Date: 2026-01-01 18:00:49.783428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9d4dd555ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envelope', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envelope', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
