"""Initial migration

Revision ID: 0a9d4dd555ac
Revises: 
Create Date: 2026-01-01 18:00:49.783428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9d4dd555ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'envelope',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('balance', sa.Numeric(12, 2), nullable=False),
        sa.Column('base_amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('mode', sa.String(length=16), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
    )
    op.create_table(
        'system_state',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('last_funded_month', sa.String(length=7), nullable=False),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_state')
    op.drop_table('envelope')

    # ### end Alembic commands ###
