"""add transactions and archived at

Revision ID: 746aaad7ffa2
Revises: 0a9d4dd555ac
Create Date: 2026-01-09 19:50:04.722088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746aaad7ffa2'
down_revision = '0a9d4dd555ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envelope_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelope.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('envelope', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envelope', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    op.drop_table('transaction')
    # ### end Alembic commands ###
